### ISSUE TITLE
mac docker install failed, nothing installed

### ISSUE THREAD

**Issue by huahuayu** [crytic/solc-select#33]
run `docker run --read-only -i --rm --entrypoint='/bin/sh' trailofbits/solc-select:latest -c 'cat /usr/bin/install.sh' | bash -e` as README says, in mac osx 10.15.6, docker 19.03.13

nothing happend, no new container, no `solc` command found (even start a new termial tab)

![image](https://user-images.githubusercontent.com/1725060/98783079-ec38a780-2433-11eb-88ce-4ce0a3e3c06b.png)

**Comment by huahuayu** [comment]
also use linux command in mac is no use

```bash
git clone https://github.com/crytic/solc-select.git
./solc-select/scripts/install.sh
export PATH=$HOME/.solc-select:$PATH
```

**Comment by tommyz7** [comment]
#34 should fix this. Remember to [build from the source](https://github.com/crytic/solc-select#installation-from-source-on-os-x). You can use the PR #34 or clone from this fork https://github.com/tommyz7/solc-select

**Comment by huahuayu** [comment]
@tommyz7 thx tommy, now I am not in a hurry, I have `solc` installed in VM, when it will be updated to docker hub? then I will try.

**Comment by adrianmcli** [comment]
I am still experiencing this problem. I saw that #34 was merged 9 days ago.

I am actually using macOS Mojave (v10.14.6) though.

**Comment by huahuayu** [comment]
hi @adrianmcli I am waiting for your good news, I still use `solc-select` in ubuntu vm.

**Comment by adrianmcli** [comment]
> hi @adrianmcli I am waiting for your good news, I still use `solc-select` in ubuntu vm.

:(

This is very sad. I might need to buy a new computer (my only computer is a Mac).

**Comment by huahuayu** [comment]
@adrianmcli no you don't, you just need a linux docker container

**Comment by rmi7** [comment]
Hey guys. We recently added a python-based experimental version of solc-select which does not use Docker. Checkout this PR: https://github.com/crytic/solc-select/pull/38 for what changed. It's already merged and inside the `experimental/bin` folder, so cloning this repo or pulling to get the latest changes should give you this newer version.

You need to put that `experimental/bin` folder in your `PATH`, and then it should just work.
```
# my .bashrc
export PATH=/Users/username/somedir/solc-select/experimental/bin:$PATH
```

**Comment by arcz** [comment]
This shouldn't happen anymore, see https://github.com/crytic/solc-select/releases/tag/0.2.0.
